# Migration summary — archive → ADR (2026-04-17)

This file records consolidation actions taken on 2026-04-17 to centralize decision texts in `docs/ADR/`.

## Migrated items

- `docs/archive/architecture-legacy/runtime_authority_decision.md` → `docs/ADR/adr-0001-runtime-authority-in-world-engine.md`
  - Reason: canonical runtime authority decision consolidated into ADR-0001; ADR contains the authoritative decision summary, ownership boundaries, and migration policy.

## Candidate archive/spec files referencing decision content (manual review recommended)

- `docs/archive/documentation-consolidation-2026/DURABLE_TRUTH_MIGRATION_VERIFICATION_TABLE.md`
- `docs/archive/documentation-consolidation-2026/DURABLE_TRUTH_MIGRATION_LEDGER.md`
- `docs/archive/superpowers-legacy-execution-2026/specs/2026-03-29-w2-4-4-role-diagnostics.md` (contains decision/diagnostic items)
- `docs/archive/superpowers-legacy-execution-2026/specs/2026-03-28-w2-2-2-mutation-policy-design.md` (audit / decision traces)

## Next steps recommended

- Replace archived decision files with short pointer notes to their canonical `docs/ADR/*` entry (avoid duplicating decision text).
- For each candidate file above, extract any explicit decision summaries into named ADRs (create `adr-00XX` files) or append as "Migrated Decision" sections into an existing ADR when semantically identical.
- Update cross-references in the docs tree to point to `docs/ADR/*` instead of archived files.
- Optionally mark archived originals as `ARCHIVED: see ADR-XXXX` to preserve evidence while avoiding duplication.

---

Generated by automation to consolidate ADR content. If you want, I can (A) create pointer notes in the archive files, (B) extract decision blocks into new ADR files, or (C) run another pass and create a CSV report of all candidate files. Which should I do next?